// ===== CHARACTER IMAGES =====
const CHARACTER_IMAGES = {
  'Daenerys Targaryen': '/images/characters/daenerys-targaryen.jpg',
  'Samwell Tarly': '/images/characters/samwell-tarly.jpg',
  'Jon Snow': '/images/characters/jon-snow.jpg',
  'Arya Stark': '/images/characters/arya-stark.jpg',
  'Sansa Stark': '/images/characters/sansa-stark.jpg',
  'Eddard Stark': '/images/characters/eddard-stark.jpg',
  'Robert Baratheon': '/images/characters/robert-baratheon.jpg',
  'Jaime Lannister': '/images/characters/jaime-lannister.jpg',
  'Cersei Lannister': '/images/characters/cersei-lannister.jpg',
  'Catelyn Stark': '/images/characters/catelyn-stark.jpg',
  'Robb Stark': '/images/characters/robb-stark.jpg',
  'Theon Greyjoy': '/images/characters/theon-greyjoy.jpg',
  'Joffrey Baratheon': '/images/characters/joffrey-baratheon.jpg',
  'Tyrion Lannister': '/images/characters/tyrion-lannister.jpg',
  'Sandor Clegane': '/images/characters/sandor-clegane.jpg',
  'Petyr Baelish': '/images/characters/petyr-baelish.jpg',
  'Davos Seaworth': '/images/characters/davos-seaworth.jpg',
  'Stannis Baratheon': '/images/characters/stannis-baratheon.jpg',
  'Varys': '/images/characters/varys.jpg',
  'Khal Drogo': '/images/characters/khal-drogo.jpg',
  'Margaery Tyrell': '/images/characters/margaery-tyrell.jpg',
  'Ygritte': '/images/characters/ygritte.jpg',
  'Brienne of Tarth': '/images/characters/brienne-of-tarth.jpg',
  'Missandei': '/images/characters/missandei.jpg',
  'Gilly': '/images/characters/gilly.jpg',
  'Viserys Targaryen': '/images/characters/viserys-targaryen.jpg',
  'Rickon Stark': '/images/characters/rickon-stark.jpg',
  'Roose Bolton': '/images/characters/roose-bolton.jpg',
  'Daario Naharis': '/images/characters/daario-naharis.jpg',
  'Shae': '/images/characters/shae.jpg',
  'Tommen Baratheon': '/images/characters/tommen-baratheon.jpg',
  'Gendry': '/images/characters/gendry.jpg',
  'Jorah Mormont': '/images/characters/jorah-mormont.jpg',
  'Ramsay Bolton': '/images/characters/ramsay-bolton.jpg',
  'Ramsay Snow': '/images/characters/ramsay-bolton.jpg',
  'Talisa Stark': '/images/characters/talisa-stark.jpg',
  'Jeor Mormont': '/images/characters/jeor-mormont.jpg',
  'High Sparrow': '/images/characters/high-sparrow.jpg',
  'Oberyn Martell': '/images/characters/oberyn-martell.jpg',
  'Melisandre': '/images/characters/melisandre.jpg',
  'Jaqen H\'ghar': '/images/characters/jaqen-hghar.jpg',
  'Tywin Lannister': '/images/characters/tywin-lannister.jpg',
  'Ellaria Sand': '/images/characters/ellaria-sand.jpg',
  'Tormund Giantsbane': '/images/characters/tormund.jpg',
  'Tormund': '/images/characters/tormund.jpg',
  'Yara Greyjoy': '/images/characters/yara-greyjoy.jpg',
  'Euron Greyjoy': '/images/characters/euron-greyjoy.jpg',
  'Hodor': '/images/characters/hodor.jpg',
  'Pycelle': '/images/characters/pycelle.jpg',
  'Grey Worm': '/images/characters/grey-worm.jpg',
  'Olenna Tyrell': '/images/characters/olenna-tyrell.jpg',
  'Qyburn': '/images/characters/qyburn.jpg',
  'Bronn': '/images/characters/bronn.jpg',
};

// ===== CHARACTER DESCRIPTIONS =====
const CHARACTER_DESCRIPTIONS = {
  'Daenerys Targaryen': 'Mother of Dragons, Khaleesi of the Great Grass Sea, and the last known Targaryen heir who conquered Westeros with her three dragons.',
  'Jon Snow': 'The bastard son of Ned Stark — or so everyone believed. Raised at Winterfell, he joined the Night\'s Watch and became its Lord Commander before being revealed as Aegon Targaryen.',
  'Arya Stark': 'The youngest Stark daughter who trained as a Faceless Man assassin in Braavos. Known for her fierce independence and deadly skills.',
  'Sansa Stark': 'The eldest Stark daughter who endured captivity in King\'s Landing and Winterfell before becoming Queen in the North.',
  'Tyrion Lannister': 'The sharp-witted dwarf of House Lannister, known as "The Imp." Despite being scorned by his family, he served as Hand of the King.',
  'Cersei Lannister': 'Queen of the Seven Kingdoms and twin sister of Jaime Lannister. Ruthless in her quest for power and fiercely protective of her children.',
  'Jaime Lannister': 'The Kingslayer — one of the greatest swordsmen in Westeros. A member of the Kingsguard who killed the Mad King Aerys.',
  'Eddard Stark': 'Lord of Winterfell and Warden of the North. Ned was known for his unwavering honor, which ultimately led to his execution in King\'s Landing.',
  'Robert Baratheon': 'King of the Seven Kingdoms who won the Iron Throne by rebellion. Once a fierce warrior, he grew into a drunken and neglectful ruler.',
  'Robb Stark': 'The Young Wolf — King in the North who won every battle but lost the war at the Red Wedding.',
  'Theon Greyjoy': 'Ward of Winterfell and heir to the Iron Islands. Betrayed the Starks before being broken and remade as "Reek" by Ramsay Bolton.',
  'Joffrey Baratheon': 'The cruel boy king who sat on the Iron Throne. Officially a Baratheon, but secretly the product of Jaime and Cersei\'s incest.',
  'Sandor Clegane': 'The Hound — scarred by his brother, he served as Joffrey\'s bodyguard before abandoning the crown. Known for his brutal honesty.',
  'Petyr Baelish': 'Littlefinger — the master manipulator who rose from minor nobility to become one of the most powerful men in Westeros.',
  'Varys': 'The Spider — Master of Whisperers, a eunuch spymaster who claims to serve the realm above all else.',
  'Khal Drogo': 'A powerful Dothraki warlord who married Daenerys Targaryen. His death set her on the path to becoming Mother of Dragons.',
  'Tywin Lannister': 'Lord of Casterly Rock and the most feared man in Westeros. The calculating patriarch of House Lannister.',
  'Samwell Tarly': 'Jon Snow\'s closest friend. A self-described coward who became a hero — the first man in thousands of years to slay a White Walker.',
  'Catelyn Stark': 'Lady of Winterfell and mother of the Stark children. Fiercely devoted to her family, she was murdered at the Red Wedding.',
  'Davos Seaworth': 'The Onion Knight — a former smuggler who became one of the most loyal advisors in Westeros, serving Stannis and later Jon Snow.',
  'Stannis Baratheon': 'The rightful heir to the Iron Throne after Robert\'s death. A just but inflexible military commander consumed by his claim.',
  'Margaery Tyrell': 'The ambitious Rose of Highgarden who married three kings. Known for her political cunning and charm.',
  'Ygritte': 'A wildling spearwife who fell in love with Jon Snow beyond the Wall. Famous for her catchphrase: "You know nothing, Jon Snow."',
  'Brienne of Tarth': 'The Maid of Tarth — one of the greatest warriors in Westeros. A woman knight sworn to honor and duty.',
  'Jorah Mormont': 'A disgraced knight who became Daenerys\'s most devoted protector. Exiled from Bear Island, he sought redemption through service.',
  'Melisandre': 'The Red Woman — a priestess of R\'hllor with mysterious powers including shadow magic and resurrection.',
  'Oberyn Martell': 'The Red Viper of Dorne — a skilled warrior and lover who sought vengeance for his sister Elia\'s murder.',
  'Ramsay Bolton': 'The sadistic bastard of Roose Bolton, known for his cruelty and torture. Legitimized as a Bolton heir.',
  'Missandei': 'A former slave from Naath who served as Daenerys\'s most trusted advisor and translator.',
  'Grey Worm': 'Commander of the Unsullied who served Daenerys. Born a slave, he chose his own name and fought for freedom.',
  'Hodor': 'Winterfell\'s gentle giant who could only say one word: "Hodor." His tragic origin was revealed as "Hold the door."',
  'Olenna Tyrell': 'The Queen of Thorns — the sharp-tongued matriarch of House Tyrell. A political mastermind who poisoned Joffrey.',
  'Gendry': 'The last surviving bastard of Robert Baratheon. A skilled blacksmith who was legitimized as Lord of Storm\'s End.',
  'Bronn': 'A sellsword with a sharp blade and sharper tongue. Rose from nothing to become Lord of Highgarden through cunning loyalty.',
  'Viserys Targaryen': 'Daenerys\'s abusive brother who sold her to Khal Drogo in exchange for an army. Received his "golden crown" of molten gold.',
  'Roose Bolton': 'The cold, calculating Lord of the Dreadfort who betrayed Robb Stark at the Red Wedding.',
  'Euron Greyjoy': 'The mad pirate king of the Iron Islands. Self-proclaimed "greatest captain in the fourteen seas."',
  'Yara Greyjoy': 'Theon\'s fierce sister and a skilled sea captain. She claimed the Salt Throne and allied with Daenerys.',
  'Tommen Baratheon': 'The gentle young king manipulated by all around him. Took his own life after witnessing the destruction of the Great Sept.',
  'Shae': 'A camp follower turned handmaiden who became Tyrion\'s lover. Her betrayal in court led to tragic consequences.',
  'Rickon Stark': 'The youngest Stark child whose fate was sealed by Ramsay Bolton\'s cruelty in the Battle of the Bastards.',
  'Talisa Stark': 'A healer from Volantis who married Robb Stark against political wisdom. Murdered at the Red Wedding.',
  'Jeor Mormont': 'The Old Bear — Lord Commander of the Night\'s Watch and father figure to Jon Snow.',
  'High Sparrow': 'The leader of the Faith Militant who challenged the crown\'s authority in King\'s Landing.',
  'Daario Naharis': 'A charismatic sellsword captain of the Second Sons who became Daenerys\'s lover in Meereen.',
  'Ellaria Sand': 'Oberyn Martell\'s paramour who sought revenge for his death by poisoning Myrcella Baratheon.',
  'Pycelle': 'Grand Maester of King\'s Landing who served on the Small Council for decades, secretly loyal to House Lannister.',
  'Qyburn': 'A disgraced maester who became Cersei\'s most loyal advisor. Creator of the undead Mountain.',
  'Gilly': 'A wildling woman rescued by Samwell Tarly from Craster\'s Keep. Mother to Little Sam.',
};

// ===== HOUSE SIGIL DESCRIPTIONS (coat of arms text from API) =====
const HOUSE_COLORS = {
  'House Stark': { primary: '#8c9aa0', secondary: '#ffffff', accent: '#3a4f5c' },
  'House Lannister': { primary: '#c9a84c', secondary: '#8b0000', accent: '#d4a836' },
  'House Targaryen': { primary: '#8b0000', secondary: '#1a1a1a', accent: '#ff4500' },
  'House Baratheon': { primary: '#b8860b', secondary: '#1a1a1a', accent: '#d4a836' },
  'House Tyrell': { primary: '#2e7d32', secondary: '#b8860b', accent: '#4caf50' },
  'House Martell': { primary: '#ff8c00', secondary: '#8b0000', accent: '#ffd700' },
  'House Greyjoy': { primary: '#b8860b', secondary: '#1a1a1a', accent: '#d4a836' },
  'House Tully': { primary: '#1565c0', secondary: '#8b0000', accent: '#42a5f5' },
  'House Arryn': { primary: '#1976d2', secondary: '#ffffff', accent: '#64b5f6' },
  'House Bolton': { primary: '#8b0000', secondary: '#e91e63', accent: '#c62828' },
  'House Mormont': { primary: '#2e7d32', secondary: '#1a1a1a', accent: '#388e3c' },
  'House Frey': { primary: '#607d8b', secondary: '#37474f', accent: '#78909c' },
  'House Tarly': { primary: '#2e7d32', secondary: '#8b0000', accent: '#4caf50' },
};

// ===== DRAGONS DATA =====
export const DRAGONS = [
  {
    name: 'Drogon',
    rider: 'Daenerys Targaryen',
    color: 'Black with red markings',
    status: 'Alive',
    namedAfter: 'Khal Drogo',
    image: '/images/dragons/drogon.jpg',
    description: 'The largest and most aggressive of Daenerys\'s three dragons. Black scales with red horns and wings. He became Daenerys\'s personal mount and the most feared creature in the known world.',
    colorClass: 'from-red-900 via-red-800 to-gray-900',
    borderColor: 'border-red-700',
    glowColor: 'shadow-red-900/50',
  },
  {
    name: 'Rhaegal',
    rider: 'Jon Snow (Aegon Targaryen)',
    color: 'Green with bronze markings',
    status: 'Dead — killed by Euron Greyjoy\'s scorpion bolt',
    namedAfter: 'Rhaegar Targaryen',
    image: '/images/dragons/rharegal.jpg',
    description: 'Named after Daenerys\'s eldest brother. Green and bronze in color, Rhaegal was ridden by Jon Snow, the secret Targaryen heir, during the Battle of Winterfell.',
    colorClass: 'from-green-900 via-green-800 to-gray-900',
    borderColor: 'border-green-700',
    glowColor: 'shadow-green-900/50',
  },
  {
    name: 'Viserion',
    rider: 'The Night King (formerly Daenerys)',
    color: 'Cream and gold → Ice blue (after resurrection)',
    status: 'Dead — killed by Arya destroying the Night King',
    namedAfter: 'Viserys Targaryen',
    image: '/images/dragons/viserion.jpg',
    description: 'Originally cream and gold colored, Viserion was killed by the Night King beyond the Wall and resurrected as an ice dragon. He destroyed the Wall at Eastwatch, allowing the Army of the Dead to invade Westeros.',
    colorClass: 'from-blue-900 via-cyan-800 to-gray-900',
    borderColor: 'border-cyan-600',
    glowColor: 'shadow-cyan-900/50',
  },
  {
    name: 'Balerion the Black Dread',
    rider: 'Aegon I Targaryen, Visenya Targaryen, Maegor I, others',
    color: 'Black',
    status: 'Dead — died of old age (~200 years old)',
    namedAfter: 'The Valyrian god Balerion',
    image: '/images/dragons/balerion.jpg',
    description: 'The largest dragon in the history of Westeros. His flames forged the Iron Throne and his shadow could cover entire towns. Balerion carried Aegon the Conqueror during the War of Conquest.',
    colorClass: 'from-gray-900 via-gray-800 to-black',
    borderColor: 'border-gray-600',
    glowColor: 'shadow-gray-800/50',
  },
  {
    name: 'Meraxes',
    rider: 'Rhaenys Targaryen',
    color: 'Silver with golden eyes',
    status: 'Dead — killed during the First Dornish War',
    namedAfter: 'Old Valyrian god',
    image: '/images/dragons/meraxes.jpg',
    description: 'One of the three dragons used in Aegon\'s Conquest. Meraxes was ridden by Queen Rhaenys Targaryen and was nearly as large as Balerion. She was killed by a scorpion bolt through the eye at Hellholt in Dorne.',
    colorClass: 'from-gray-700 via-yellow-900 to-gray-800',
    borderColor: 'border-yellow-700',
    glowColor: 'shadow-yellow-900/50',
  },
  {
    name: 'Vhagar',
    rider: 'Visenya Targaryen, Laena Velaryon, Aemond Targaryen',
    color: 'Bronze with blue-green highlights',
    status: 'Dead — killed during the Dance of the Dragons',
    namedAfter: 'Old Valyrian god',
    image: '/images/dragons/rhagar.jpg',
    description: 'The largest living dragon during the Dance of the Dragons, nearly rivaling Balerion in size. Vhagar was ridden by Visenya during the Conquest and later by Aemond One-Eye during the Targaryen civil war.',
    colorClass: 'from-teal-900 via-amber-900 to-gray-900',
    borderColor: 'border-amber-700',
    glowColor: 'shadow-amber-900/50',
  },
];

// ===== VALYRIAN STEEL SWORDS =====
export const VALYRIAN_SWORDS = [
  {
    name: 'Ice',
    house: 'House Stark',
    owner: 'Eddard Stark',
    type: 'Greatsword',
    status: 'Melted down — reforged into Widow\'s Wail and Oathkeeper',
    description: 'The ancestral greatsword of House Stark, used by the Lords of Winterfell for generations. An enormous two-handed blade used for ceremonial executions. Seized by the Lannisters after Ned\'s death and melted down by Tywin.',
    image: '/images/swords/ice.jpg',
    color: 'from-gray-400 via-blue-200 to-gray-500',
  },
  {
    name: 'Longclaw',
    house: 'House Mormont → Jon Snow',
    owner: 'Jon Snow',
    type: 'Bastard sword (hand-and-a-half)',
    status: 'Active',
    description: 'The ancestral sword of House Mormont for five centuries. Given to Jon Snow by Lord Commander Jeor Mormont after Jon saved him from a wight. Features a white wolf pommel replacing the original bear.',
    image: '/images/swords/long.jpg',
    color: 'from-gray-300 via-white to-gray-400',
  },
  {
    name: 'Widow\'s Wail',
    house: 'House Lannister/Baratheon',
    owner: 'Joffrey Baratheon → Jaime Lannister',
    type: 'Longsword',
    status: 'Active',
    description: 'One of two swords reforged from Ice by Tywin Lannister. Given to King Joffrey as a wedding gift. After Joffrey\'s death, it passed to Jaime Lannister who wielded it in the Great War.',
    image: '/images/swords/widows.jpg',
    color: 'from-red-400 via-yellow-300 to-red-500',
  },
  {
    name: 'Oathkeeper',
    house: 'House Lannister → Brienne of Tarth',
    owner: 'Brienne of Tarth',
    type: 'Longsword',
    status: 'Active',
    description: 'The second sword reforged from Ice. Jaime Lannister gave it to Brienne along with a quest to find and protect Sansa Stark. Named by Brienne to honor her oath to Catelyn Stark.',
    image: '/images/swords/oath.jpg',
    color: 'from-yellow-400 via-yellow-200 to-yellow-500',
  },
  {
    name: 'Heartsbane',
    house: 'House Tarly',
    owner: 'Samwell Tarly',
    type: 'Greatsword',
    status: 'Active',
    description: 'The ancestral Valyrian steel greatsword of House Tarly. Stolen by Samwell from his father Randyll Tarly\'s keep at Horn Hill to use in the fight against the White Walkers.',
    image: '/images/swords/heartsbane.jpg',
    color: 'from-green-400 via-green-200 to-green-500',
  },
  {
    name: 'Dark Sister',
    house: 'House Targaryen',
    owner: 'Visenya Targaryen, Daemon Targaryen, Brynden Rivers',
    type: 'Longsword',
    status: 'Unknown — last wielded by Bloodraven',
    description: 'A famous Targaryen blade first wielded by Queen Visenya during Aegon\'s Conquest. A slender sword suited for a woman\'s hand. Last known to be in possession of Brynden "Bloodraven" Rivers.',
    image: '/images/swords/darksis.jpg',
    color: 'from-purple-400 via-red-300 to-purple-600',
  },
  {
    name: 'Blackfyre',
    house: 'House Targaryen → House Blackfyre',
    owner: 'Aegon I Targaryen, Daemon Blackfyre',
    type: 'Longsword',
    status: 'Unknown — lost after the Blackfyre Rebellions',
    description: 'The personal sword of Aegon the Conqueror and the blade from which House Blackfyre took its name. Traditionally passed from king to king, its gifting to Daemon Blackfyre sparked a rebellion.',
    image: '/images/swords/blackfyre.jpg',
    color: 'from-gray-800 via-red-900 to-black',
  },
  {
    name: 'Lady Forlorn',
    house: 'House Corbray',
    owner: 'Lyn Corbray',
    type: 'Longsword',
    status: 'Active',
    description: 'The ancestral sword of House Corbray of the Vale. Wielded by Ser Lyn Corbray, a noted swordsman secretly in the pay of Petyr Baelish.',
    image: '/images/swords/forlorn.jpg',
    color: 'from-blue-400 via-gray-300 to-blue-500',
  },
];

// ===== FUNCTIONS =====

export function getCharacterImage(name) {
  if (!name) return null;
  return CHARACTER_IMAGES[name] || null;
}

export function getCharacterDescription(name) {
  if (!name) return null;
  return CHARACTER_DESCRIPTIONS[name] || null;
}

export function getHouseColors(houseName) {
  if (!houseName) return null;
  return HOUSE_COLORS[houseName] || null;
}

export function getInitials(name) {
  if (!name) return '?';
  return name
    .split(' ')
    .filter((w) => !['of', 'the'].includes(w.toLowerCase()))
    .map((w) => w[0])
    .slice(0, 2)
    .join('')
    .toUpperCase();
}
